theme: jekyll-theme-cayman

# Setup
title:               Line 47 Website
tagline:             Do we really need a tagline
url:                 http://line47.github.io/
baseurl:             /line47.github.io/


# Set the Sass partials directory, as we're using @imports
sass:
    sass_dir: _sass
