
# Setup
title: Line 47 Website
tagline:
baseurl: /
collections:
  work:
    output: true
    permalink: /work/:slug
  featuredwork:
    output: true
    permalink: /work/:slug
  projects:
    output: true
    permalink: /work/:slug
  articles:
    output: false
    
